version: '3'

services:
  dns-server:
    container_name: dns-server
    build:
      context: .
      dockerfile: ./dns/Dockerfile
    ports:
      - 5300:53
    networks:
      net1:
        ipv4_address: 172.16.0.1

  time-server:
    container_name: time-server
    build:
      context: .
      dockerfile: ./TimeServer/Dockerfile
    ports:
      - 7070:7070
    networks:
      net1:
        ipv4_address: 172.16.0.3
  time-client:
    container_name: time-client
    build:
      context: .
      dockerfile: ./TimeClient/Dockerfile
    volumes:
      - type: bind
        source: ./compiled_jars
        target: /app/compiled_jars

  daytime-server:
    container_name: daytime-server
    build:
      context: .
      dockerfile: ./DayTimeServer/Dockerfile
    ports:
      - 4040:4040
    networks:
      net1:
        ipv4_address: 172.16.0.4
  daytime-client:
    container_name: daytime-client
    build:
      context: .
      dockerfile: ./DayTimeClient/Dockerfile
    volumes:
      - type: bind
        source: ./compiled_jars
        target: /app/compiled_jars

  dummy:
    container_name: dummy
    depends_on:
      dns-server:
        condition: service_started
      time-server:
        condition: service_started
      time-client:
        condition: service_completed_successfully
      daytime-server:
        condition: service_started
      daytime-client:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: ./dummy/Dockerfile
    networks:
      net1:
        ipv4_address: 172.16.0.2
    command: sh -c "echo 'nameserver 172.16.0.1' > /etc/resolv.conf && tail -f /dev/null"
    volumes:
      - ./compiled_jars:/app

networks:
  net1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
          gateway: 172.16.1.1